const StepType = Object.freeze({
  GLOBAL_CTX_CREATE: 'GLOBAL_CTX_CREATE',
  VAR_HOIST: 'VAR_HOIST',
  FN_HOIST: 'FN_HOIST',
  LET_CONST_DECLARE: 'LET_CONST_DECLARE',
  ASSIGN: 'ASSIGN',
  FN_CALL: 'FN_CALL',
  FN_CTX_CREATE: 'FN_CTX_CREATE',
  SCOPE_CHAIN_FORM: 'SCOPE_CHAIN_FORM',
  CLOSURE_CAPTURE: 'CLOSURE_CAPTURE',
  FN_RETURN: 'FN_RETURN',
  LOG: 'LOG',
  LOOP_START: 'LOOP_START',
  LOOP_ITER: 'LOOP_ITER',
  LOOP_END: 'LOOP_END',
  IF_TRUE: 'IF_TRUE',
  IF_FALSE: 'IF_FALSE',
  TIMEOUT_REGISTER: 'TIMEOUT_REGISTER',
  TIMEOUT_FIRE: 'TIMEOUT_FIRE',
  CB_DEQUEUE: 'CB_DEQUEUE',
  PROGRAM_END: 'PROGRAM_END',
});

export default StepType;